/**:
  ros__parameters:
    color_range_list:
      black:
        max:
         - 81
         - 227
         - 255
        min:
         - 0
         - 0
         - 0
      blue:
        max:
         - 166
         - 255
         - 121
        min:
         - 0
         - 0
         - 2
      green:
        max:
         - 172
         - 119
         - 182
        min:
         - 0
         - 0
         - 89
      red:
        max:
         - 141
         - 255
         - 238
        min:
         - 8
         - 137
         - 116
      white:
        max:
         - 56
         - 255
         - 255
        min:
         - 0
         - 0
         - 128
